server {
    listen 8080; # Cloud Run uses 8080 by default

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/users/ {
        proxy_pass https://user-service-911534372370.us-central1.run.app/api/users/;
        proxy_set_header Host user-service-911534372370.us-central1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/workouts/ {
        proxy_pass https://workout-service-911534372370.us-central1.run.app/api/workouts/;
        proxy_set_header Host workout-service-911534372370.us-central1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ai/ {
        proxy_pass https://ai-coach-service-911534372370.us-central1.run.app/api/ai/;
        proxy_set_header Host ai-coach-service-911534372370.us-central1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
