[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::PendingDeprecationWarning:starlette.formparsers
    ignore::DeprecationWarning:pytest_asyncio.plugin
    ignore:The event_loop fixture provided by pytest-asyncio has been redefined:DeprecationWarning
